### ISSUE TITLE
Command or interactive command error on missing git add

### ISSUE THREAD

**Issue by 404answernotfound** [TheJoin95/wdyd#2]
The command (tried interactive) does not take into account the missing "git add" that's needed before any commits can be sent, generating an error.

I tried this with a newly created repository, without git add.
![Schermata 2022-07-28 alle 18 16 21](https://user-images.githubusercontent.com/79904453/181587558-188a7943-d435-4620-867e-0aed5b61d6ab.png)
![Schermata 2022-07-28 alle 18 16 15](https://user-images.githubusercontent.com/79904453/181587561-a3dc8f80-d0a4-4219-993b-63a11fc1a803.png)

**Comment by TheJoin95** [comment]
I was thinking on this because eventually I would like to add just a couple of files not all for a single commit.

It may happen that someone new to git or software development is doing it's changes all in a round than commit file by file. What do you think? Shall we add the `git add .` command?

**Comment by 404answernotfound** [comment]
> I was thinking on this because eventually I would like to add just a couple of files not all for a single commit.
> 
> It may happen that someone new to git or software development is doing it's changes all in a round than commit file by file. What do you think? Shall we add the `git add .` command?

I was thinking we could check, somehow, whether or not the "git add ." or "git add *" or "git add singlefile" was done by the user, if not print a warning and exit the shell cmd

We could regex search for this "git status" string -> nothing added to commit but untracked files present (use "git add" to track)

If present, we warn the user and exit the cmd

**Comment by TheJoin95** [comment]
Uhm, yes, I agree on this way of managing the case

**Comment by 404answernotfound** [comment]
possibly fixed with PR #4 

can you check it out?
